tasks:
    hello:
        name: Hello World
        command: |
            echo "Hello, World!"
        triggeredBy:
        - manual
        # - postEnvironmentStart
        # - postDevcontainerStart
    setup-git-user:
        name: Setup git user
        command: |
            source .gitpod/git.env && 
            git config --global user.name $USER_NAME && 
            git config --global user.email $USER_EMAIL
services:
    dev:
        name: Develop Service
        description: npm run dev
        commands:
            start: |
                npm run dev -- --host 0.0.0.0
        triggeredBy:
            - postDevcontainerStart
    backend:
        name: Backend Service
        description: Example service simulating a backend
        commands:
            start: |
                echo "Starting backend service..."
                touch /tmp/backend.started
                while true; do
                    sleep 1
                    date
                done
            ready: |
                if [ -f /tmp/backend.started ]; then
                    echo "Backend service is ready"
                    exit 0
                else
                    echo "Backend service is not ready"
                    exit 1
                fi
            # stop: |
            # 	echo "Stopping backend service..."
            # 	rm /tmp/backend.started
            #   pkill backend
        triggeredBy:
            - postEnvironmentStart
            # - postDevcontainerStart
