tasks:
    setup-git-user:
        name: git config user
        command: "scripts/setup-git-user.sh"
        triggeredBy:
            - manual
            - postEnvironmentStart
services:
    dev:
        name: Develop Service
        description: npm run dev
        commands:
            start: |
                npm run dev -- --host 0.0.0.0
        triggeredBy:
            - postDevcontainerStart